version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: devops-mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 12

  ventas:
    build:
      context: .
      dockerfile: Dockerfile.ventas
    container_name: ventas-api
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - appnet

  despacho:
    build:
      context: .
      dockerfile: Dockerfile.despacho
    container_name: despacho-api
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
    driver: bridge